# Generated by Django 3.2 on 2022-12-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221212_2035'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wish_list',
            field=models.ManyToManyField(
                blank=True, related_name='user_wish_list_products',
                to='products.Product'),
        ),
    ]
