# Generated by Django 3.2 on 2023-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('contents', models.FileField(
                    upload_to='uploaded_newsletters/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
