# Generated by Django 3.2 on 2023-01-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypoints',
            name='redeemedFlag',
            field=models.BooleanField(default=False),
        ),
    ]
